trigger: none
pr:
  - master
  - develop
  
variables:
  - group: docker-repo

stages:
  - stage: Build
    displayName: Build and deploy 
    pool:
      name: VM-CPU12195
    jobs:
      - job: checkVersion
        displayName: Check node and npm version
        steps:
          - task: Bash@3
            displayName: Check node and npm version
            inputs:
              targetType: inline
              script: |
                node -v
                npm -v
                echo $(Build.Repository.LocalPath)
      - job: build_be_image
        displayName: Build Backend image
        steps:
          - task: Docker@2
            displayName: Login to Docker Hub
            inputs:
              command: login
              containerRegistry: $(containerRegistry)
          - task: Docker@2
            displayName: Build image
            inputs:
              command: build
              repository: $(repository)
              Dockerfile: backend/Dockerfile
              buildContext: backend/
              tags:
                $(tag)

