trigger: none
pr:
  - master
  - develop
  
stages:
  - stage: Build
    displayName: Build and deploy 
    pool:
      name: VM-CPU12195
    jobs:
      - job: checkVersion
        displayName: Check node and npm version
        steps:
          - task: Bash@3
            displayName: Check node and npm version
            inputs:
              targetType: inline
              script: |
                node -v
                npm -v
