trigger: 
  branches:
    include:
      - develop
      - master
  paths:
    include:
      - backend/*
      - frontend/*
  
variables:
  - group: 'BK Delivery System'

stages:
- stage: Build_Docker_Images
  pool:
    name: CPU13085
  jobs:
  - job: Build_Linux_Alpha
    displayName: 'Linux: Build DockerImages Alpha'
    condition: |
      or
      (
        and( eq(variables['Build.Reason'], 'Manual'), eq(variables['Flavor'], 'dev') ),
        and
        (
          ne(variables['Build.Reason'], 'Manual'),
          eq(variables['Build.SourceBranch'], 'refs/heads/develop')
        )
      )
    steps:
    - template: azure-devops/bds-build-steps.yaml
      parameters:
        flavor: dev

  - job: Build_Linux_Stable
    displayName: 'Linux: Build DockerImages Stable'
    condition: |
      or
      (
        and( eq(variables['Build.Reason'], 'Manual'), eq(variables['Flavor'], 'live') ),
        and
        (
          ne(variables['Build.Reason'], 'Manual'),
          eq(variables['Build.SourceBranch'], 'refs/heads/master')
        )
      )
    steps:
    - template: azure-devops/bds-build-steps.yaml
      parameters:
        flavor: live
  
- stage: Deploy_Services
  dependsOn: Build_Docker_Images
  condition: succeeded()
  pool:
    name: CPU13085
  jobs:
  - job: Deploy_Services_Alpha
    displayName: 'Linux: Deploy Services - Alpha'
    condition: |
      or
      (
        and( eq(variables['Build.Reason'], 'Manual'), in(variables['Flavor'], 'dev', 'deploy-dev') ),
        and
        (
          ne(variables['Build.Reason'], 'Manual'),
          eq(variables['Build.SourceBranch'], 'refs/heads/develop')
        )
      )
    steps:
    - checkout: self
    - template: azure-devops/bds-deploy-steps.yaml
      parameters:
        flavor: dev

  - job: Deploy_Services_Stable
    displayName: 'Linux: Deploy Services - Stable'
    condition: |
      or
      (
        and( eq(variables['Build.Reason'], 'Manual'), in(variables['Flavor'], 'live', 'deploy-live') ),
        and
        (
          ne(variables['Build.Reason'], 'Manual'),
          eq(variables['Build.SourceBranch'], 'refs/heads/master')
        )
      )
    steps:
    - checkout: self
    - template: azure-devops/bds-deploy-steps.yaml
      parameters:
        flavor: live