trigger: none
pr:
  - master
  - develop
  
variables:
  - group: docker-repo

stages:
  - stage: Build
    displayName: Build and deploy 
    pool:
      name: VM-CPU12195
    jobs:
      - job: checkVersion
        displayName: Check node and npm version
        steps:
          - task: Bash@3
            displayName: Check node and npm version
            inputs:
              targetType: inline
              script: |
                node -v
                npm -v
                echo $(Build.Repository.LocalPath)
      - job: build_be_image
        displayName: Build Backend image
        steps:
          - task: Bash@3
            displayName: Copy .env to build directory
            inputs:
              targetType: inline
              script: |
                chmod +x copy-env.sh
                . ./copy-env.sh
          - task: Docker@2
            displayName: Login to Docker Hub
            inputs:
              command: login
              containerRegistry: $(containerRegistry)
          - task: Docker@2
            displayName: Build image
            inputs:
              command: build
              repository: $(repoBackend)
              Dockerfile: backend/Dockerfile
              buildContext: backend/
              tags:
                $(tag)
          - task: Bash@3
            displayName: Create an container for testing
            inputs:
              targetType: inline
              script: docker container run -d --name healthcheck -p 5000:5000 $(repoBackend):$(tag) 
          - task: Bash@3
            displayName: Health check
            inputs:
              targetType: inline
              script: |
                chmod +x healthcheck.sh 
                . ./healthcheck.sh
          - task: Bash@3
            displayName: Remove container health check
            inputs:
              targetType: inline
              script: |
                chmod +x rm-healthcheck.sh
                . ./rm-healthcheck.sh
          - task: Docker@2
            displayName: Push image to Docker Hub
            inputs:
              command: push
              repository: $(repoBackend)
              tags: 
                $(tag)
          - task: Bash@3
            displayName: Retag image to latest
            inputs:
              targetType: inline
              script: |
                docker tag $(repoBackend):$(tag) $(repoBackend):latest
          - task: Docker@2  
            displayName: Push image with latest tag
            inputs:
              command: push
              repository: $(repoBackend)
              tags: latest
          - task: Bash@3
            displayName: Remove image with tag number
            inputs:
              targetType: inline 
              script: |
                docker image rm -f $(repoBackend):$(tag)
          - task: Bash@3
            displayName: Remove image with tag latest
            inputs:
              targetType: inline
              script: |
                docker image rm -f $(repoBackend):latest
          - task: Bash@3
            displayName: Remove older Backend container
            inputs:
              targetType: inline
              script: |
                chmod +x rm-old-be-container.sh
                . ./rm-old-be-container.sh
          - task: Bash@3
            displayName: Run Backend image
            inputs:
              targetType: inline
              script: |
                docker run -d -p 5000:5000 --name backend $(repoBackend):latest

