trigger:
  - develop
  - master

variables:
  - group: docker-repo
  - name: isDevelop
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
  - name: isMaster
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

stages:
  - stage: deploy_dev
    displayName: Deploy to develop 
    pool:
      name: CPU12195
    condition: eq(variables.isDevelop, 'true')
    jobs:
      - job: deploy_dev 
        displayName: Deploy on dev
        steps:
          - task: Bash@3
            displayName: Remove older dev FE container
            inputs:
              targetType: inline
              script: |
                chmod +x azure-devops/rm-old-dev-fe-container.sh
                . ./azure-devops/rm-old-dev-fe-container.sh
          - task: Bash@3
            displayName: Run Frontend image on develop
            inputs:
              targetType: inline
              script: |
                docker run -d -p 4000:3000 --name frontend-dev $(repoFrontend):latest

  - stage: deploy_prod
    displayName: Deploy to production
    pool:
      name: CPU12195
    condition: eq(variables.isMaster, 'true')
    jobs:
      - job: deploy_production
        displayName: Deploy to production
        steps:
          - task: Bash@3
            displayName: Remove older prod FE container
            inputs:
              targetType: inline
              script: |
                chmod +x azure-devops/rm-old-prod-fe-container.sh
                . ./azure-devops/rm-old-prod-fe-container.sh
          - task: Bash@3
            displayName: Run Frontend image on production
            inputs:
              targetType: inline
              script: | 
                docker run -d -p 4001:3000 --name frontend-prod $(repoFrontend):latest
